### ISSUE TITLE
Move to Transitland for Data

### ISSUE THREAD

**Issue by vkoves** [TransitNetworkGroup/Transit-Network#20]
This should fix #19 and #17 ideally. Or at least help with it.

**Comment by AcademyInPeril** [comment]
For anybody looking for more info on this, Transitland's API documentation is [here](https://transit.land/documentation/datastore/api-endpoints.html).

**Comment by vkoves** [comment]
There's a lot we could do with this. For instance, showing a list of operators to choose from when booting the site via the API endpoint for operators (https://transit.land/api/v1/operators). For now we probably want to start by moving over the CTA data and then see how we would generalize that.

**Comment by vkoves** [comment]
Closing this issue, as the Transitland move was finalized and deployed.
