### ISSUE TITLE
Create Jekyll Site Pitching Transit Network

### ISSUE THREAD

**Issue by vkoves** [TransitNetworkGroup/Transit-Network#37]
Considering that the current Transit Network site is not going to be the homepage of the Transit Network project, we need to create a site that pitches Transit Network as a platform, showcasing its benefits and walking developers through the step by step instructions for how to spin up a Transit Network instance for any transit system described by GTFS data.

We should discuss what we want on the site (a basic spec) and how we want the site to look (design) before implementing (in that order).

The site would probably work well if it was hosted on GitHub Pages and powered by Jekyll.

**Comment by rjaltman** [comment]
I agree that the site would probably be best (and easiest to get started with) using GitHub Pages and Jekyll. Since this repository is part of an organization for the entire project now, should we consider moving this then to its own repository instead of just adding a gh-pages branch here?

**Comment by AcademyInPeril** [comment]
I support @rjaltman's opinion here that the site and discussion around it should be within a separate repo in the organization. If there's no opposition by the end of the day, I'll close the issue.

**Comment by vkoves** [comment]
I think until that repo has been made, this issue should be preserved.

**Comment by vkoves** [comment]
Created a repository for this called [TransitNetworkGroup.github.io](https://github.com/TransitNetworkGroup/TransitNetworkGroup.github.io). Closing this issue.
