### ISSUE TITLE
Generalize Data Read In

### ISSUE THREAD

**Issue by grant-rez** [TransitNetworkGroup/Transit-Network#8]
The rake files that are used to read in the data are too narrow for the scope of the project. The rake files need to be updated to accommodate a large number of naming conventions and data styles.  [Here](http://jasonseifer.com/2010/04/06/rake-tutorial) is a resource that talks about rake files and what to do about them.

**Comment by vkoves** [comment]
This is old and seems to be resolved, so I'm closing it.
